//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuestrasHornosEntities : DbContext
    {
        public MuestrasHornosEntities()
            : base("name=MuestrasHornosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciclo> Ciclos { get; set; }
        public virtual DbSet<Defecto> Defectos { get; set; }
        public virtual DbSet<Lote> Lotes { get; set; }
        public virtual DbSet<Muestra> Muestras { get; set; }
        public virtual DbSet<ParteCiclo> ParteCicloes { get; set; }
        public virtual DbSet<Pieza> Piezas { get; set; }
        public virtual DbSet<PruebaPieza> PruebaPiezas { get; set; }
        public virtual DbSet<Prueba> Pruebas { get; set; }
        public virtual DbSet<Sensore> Sensores { get; set; }
        public virtual DbSet<TipoSensor> TipoSensors { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
