//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumeroParte
    {
        public string No_Parte { get; set; }
        public string Detalles { get; set; }
        public string FechaAlta { get; set; }
        public string UsuarioAlta { get; set; }
    }
}
