//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParteCiclo
    {
        public string No_Parte { get; set; }
        public string Horno { get; set; }
        public int No_Ciclo { get; set; }
        public string AoB { get; set; }
        public Nullable<int> CantidadPiezasEntrantes { get; set; }
        public Nullable<int> CantidadPiezasRebraze { get; set; }
    }
}
