//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pieza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pieza()
        {
            this.PruebaPiezas = new HashSet<PruebaPieza>();
        }
    
        public int Lote { get; set; }
        public string No_Serie { get; set; }
        public string No_Parte { get; set; }
        public Nullable<int> PK_Defecto { get; set; }
        public Nullable<int> Aprobada { get; set; }
        public Nullable<int> Rebraze { get; set; }
    
        public virtual Defecto Defecto { get; set; }
        public virtual Lote Lote1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PruebaPieza> PruebaPiezas { get; set; }
    }
}
