//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruebaPieza
    {
        public string Horno { get; set; }
        public int No_Ciclo { get; set; }
        public string PosicionHorno { get; set; }
        public int No_Prueba { get; set; }
        public string ResultadoPrueba { get; set; }
        public Nullable<int> Defecto { get; set; }
        public string FechaPrueba { get; set; }
        public string Sello1 { get; set; }
        public string Sello2 { get; set; }
        public string ObservacionesPrueba { get; set; }
        public string FirmaInspector { get; set; }
        public string ObservacionesInspector { get; set; }
    }
}
