//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muestra
    {
        public int PK_Muestra { get; set; }
        public int PK_Sensor { get; set; }
        public string Horno { get; set; }
        public int No_Ciclo { get; set; }
        public string Hora { get; set; }
        public Nullable<double> Dato { get; set; }
    
        public virtual Ciclo Ciclo { get; set; }
        public virtual Sensore Sensore { get; set; }
    }
}
