//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servidor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruebaPieza
    {
        public int PK_PruebaP { get; set; }
        public int PK_Prueba { get; set; }
        public string FechaPrueba { get; set; }
        public string FechaCaptura { get; set; }
        public int Aprobada { get; set; }
        public Nullable<int> Defecto { get; set; }
        public string No_Serie { get; set; }
    
        public virtual Pieza Pieza { get; set; }
        public virtual Prueba Prueba { get; set; }
    }
}
